### ISSUE TITLE
Push this back to geopandas?

### ISSUE THREAD

**Issue by snowman2** [awburgess/geopandas-postgis#7]
Just found this on a google search when I came across this issue: https://gis.stackexchange.com/questions/336220/dataframe-of-points-to-postgis/336712#336712

Do you have any interest in adding this back into geopandas?

It seems they are interested in this type of functionality: https://github.com/geopandas/geopandas/issues/595

**Comment by awburgess** [comment]
Sure thing. Bear with me a minute as I like to pretend that time for side projects exist between kids and day job

**Comment by jorisvandenbossche** [comment]
Just a note here: there is an active PR to add a `to_postgis` writing functionality to geopandas: https://github.com/geopandas/geopandas/pull/1248

Feedback or testing it out if it works as expected is always welcome!

**Comment by snowman2** [comment]
Closing since the geopandas MR was merged and this is no longer relevant.

**Comment by awburgess** [comment]
Thanks goodness....as I clearly was doing a great maintenance job here.... ;-)
